### ISSUE TITLE
Need an obvious button to add people

### ISSUE THREAD

**Issue by easterday** [NUDelta/DeltaWeb#4]

**Comment by kapil1garg** [comment]
Add a menu button for website admins (PIs, web head) for creating users that points to: http://delta.northwestern.edu/create_user

**Comment by kapil1garg** [comment]
fixed by @cindyhu2023 in a7d723cd358b6754b456e8c3e6b7b8525b51c10a and 37a0d37989ed755f6108628552d8b118c0c969b0!
